server:
  port: 8098
  
spring: 
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo


      