server:
  port: 8093
  
spring: 
  application:
    name: springcloud-zuul-gateway

#eureka
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://peter:admin432@localhost:8077/eureka/

#zuul
zuul:
  routes:
    springcloud-provider-user: /users/**
      