server:
  port: 8097
  
spring: 
  application:
    name: springcloud-sidecar

#eureka
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://peter:admin432@localhost:8077/eureka/

#sidecar
sidecar:
  port: 8084
  health-uri: http://localhost:8084/health  #异构平台微服务的健康检查

# =============actuator监控 =======#
management:
  endpoints:
    enabled-by-default: true # 设置端点是否可用 默认只有shutdown可用
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # include: env   # 方式1: 暴露端点 env 配置多个,隔开
        include: "*"     # 方式2: 包括所有端点, 注意需要添加引号
        # 排除端点
        exclude: shutdown 

      